#
# ███████╗░██████╗██████╗░░█████╗░░██╗░░░░░░░██╗███╗░░██╗
# ██╔════╝██╔════╝██╔══██╗██╔══██╗░██║░░██╗░░██║████╗░██║
# █████╗░░╚█████╗░██████╔╝███████║░╚██╗████╗██╔╝██╔██╗██║
# ██╔══╝░░░╚═══██╗██╔═══╝░██╔══██║░░████╔═████║░██║╚████║
# ██║░░░░░██████╔╝██║░░░░░██║░░██║░░╚██╔╝░╚██╔╝░██║░╚███║
# ╚═╝░░░░░╚═════╝░╚═╝░░░░░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝░░╚══╝
# The best slightly advanced plugin for setting up spawn.
#
#    Author: FilipeeX
#    Discord: FilipeeX#8146
#    Plugin: www.spigotmc.org/resources/104579
#

# If plugin fESSENTIALS is found, this plugin will automatically disable itself,
#   because this exact spawn feature is built into that plugin.
# Please don't mess with this option, unless you really know what you're doing.
# If this is set to false and fESSENTIALS also loads, it can create conflicts
#   between the 2 plugins and commands might not work as wanted.
# IMPORTANT: Plugin fESSENTIALS is currently not out yet,
#   so you don't have to worry about this for now..
disable-if-fessentials-is-found: true

# If an update is available, every time an admin with permission 'fspawn.update' joins the server,
#   they'll be greeted with an update message.
update-notification: true

# This option is here if self-updating the plugin
# is causing any issues to your server.
# You can turn it off, but it'll be a lot more
# work for you and something might even break when you don't update the plugin at all.
allow-self-update: true

# If a player connects to your server for the first time ever,
#   they'll be teleported to the spawn.
teleport-after-first-join: true

# Let's say a player joins the server and is teleported to the spawn.
# If that player dies and doesn't have any bed spawnpoint yet (very likely),
#   they'll respawn in a wilderness, near 0 0 at world.
# To prevent that, you can set this option to true,
#   and they'll respawn at the spawn location.
set-spawnpoint-at-spawn-after-first-join: true

# This will teleport the player to spawn every time
#   they join the server, no matter if they were alredy teleported
#   on they're first join.
# This can be VERRY EFECTIVE in HUBS and LOBBIES.
teleport-after-joining: false

# So simply if a player joins the server and fSPAWN will teleport them
#   right to spawn, there's a probability it'll become bugged.
# To bypass this, you can set a delay of ticks (20 ticks = 1 second)
#   and effectively eliminate this issue.
# To disable - set teleport delay to 0, but i really don't recommend it.
teleport-delay: 5

# If this option is enabled (true), command /fspawn reload will be enabled.
# If it's disabled, command won't be available.
# This is very useful for someone who doesn't want to reload
# plugins in this way, or doesn't wanna reload just configuration,
# but the entire plugin.
allow-fspawn-reload: true

# DON'T YOU DARE EVEN TOUCH THIS
version: 1.0.2